api_gateway_public_ip          = "api_gate_public_ip"
allocation_method              = "Static"
application_gateway_name       = "aks_application_gateway"
frontend_port_name             = "1199"
frontend_ip_configuration_name = "api_frontend_ip_configaration_name"
backend_address_pool_name      = "spring_backend_nood_pool"
http_backend_name              = "spring_http_backend_aks"
request_routing_rule_name      = "api_gate_way_rule_aks"
http_listener_name             = "gateway_http_server"
routeing_listener_name         = "gatewate_listener_aks"
backend_http_settings_name     = "aks_backend_http"


# api_gateway_public_ip          = "api_gate_public_ip"
# allocation_method              = "Static"
# application_gateway_name       = "aks_application_gateway"
# frontend_port_name             = "1199"
# frontend_ip_configuration_name = "api_frontend_ip_configaration_name"
# backend_address_pool_name      = "spring_backend_nood_pool"
# http_backend_name              = "spring_http_backend_aks"
# request_routing_rule_name      = "api_gate_way_rule_aks"
# http_listener_name             = "gateway_http_server"
# routeing_listener_name         = "gatewate_listener_aks"
# backend_http_settings_name     = "aks_backend_http"
